version: '3.8'

services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${ADMIN_USER}
      MYSQL_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${ADMIN_USER}
      WORDPRESS_DB_PASSWORD: ${ADMIN_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - wordpress:/var/www/html
    ports:
        - 80:80

volumes:
  dbdata:
  wordpress:
